# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  options,
  inputs,
  ...
}:
let
  primaryUser = config.dev.johnrinehart.users.primary;
in
{
  imports = [
    inputs.nixos-hardware.nixosModules.framework-11th-gen-intel
  ];

  dev.johnrinehart.droidcam.enable = false; # TODO: broken
  dev.johnrinehart.auto-suspend = {
    lowLevel = 30;
    criticalLevel = 20;
    notificationLevels = builtins.genList (i: 45 - (i * 5)) 6; # [ 45 40 35 30 25 20 ]
    enable = true;
  };

  nix = {
    settings = {
      extra-experimental-features = "nix-command flakes ca-derivations";
      download-buffer-size = 256 * 1024 * 1024;
      keep-outputs = true;
      trusted-users = [ primaryUser ];
    };

    distributedBuilds = true;

    buildMachines = [
      {
        hostName = "100.74.54.40";
        sshUser = primaryUser;
        protocol = "ssh-ng";
        system = "x86_64-linux";
        maxJobs = 12;
        supportedFeatures = [
          "benchmark"
          "big-parallel"
          "gccarch-alderlake"
          "gccarch-x86_64-v3"
          "gccarch-znver1"
          "gccarch-znver3"
          "kvm"
          "nixos-test"
        ];
        publicHostKey = "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUNuYlFKakdjYUExS1N3LzZSbnFxZzNlNGxwNFJtSFVKb1dpR3NXQk5lNVUgcm9vdEBuaXhvcwo=";
      }
    ];
  };

  boot.supportedFilesystems = [
    "ntfs"
    "exfat"
    "vfat"
    "btrfs"
    "ext"
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9dbd56c9-2344-450a-845b-6490d0879256";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/32F9-A71A";
    fsType = "vfat";
  };

  fileSystems."/mnt/framework250_1" = {
    device = "/dev/disk/by-uuid/caca60c2-483b-4a58-a443-5c8df3b3c82d";
    fsType = "btrfs";
    options = [
      "user"
      "rw"
      "async"
      "auto"
      "nofail"
      "x-systemd.device-timeout=2s"
    ];
  };

  # iwd manages Wi-Fi DHCP/IP configuration for this host.
  networking.hostName = "framie";
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.wlp170s0.useDHCP = lib.mkDefault false;
  dev.johnrinehart.network = {
    enable = true;
    manager = "iwd";
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  services.fwupd.enable = true;

  security.rtkit.enable = true;

  ## Below v4l2loopback stuff stolen from https://gist.github.com/TheSirC/93130f70cc280cdcdff89faf8d4e98ab
  # Extra kernel modules
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];

  # Instrument the complete USB-C -> Thunderbolt/USB4 -> DP tunnel -> MST ->
  # DRM path. Run `sudo display-link-debug snapshot failed` immediately after
  # a failure; use `diagnose`, `dynamic-debug`, and `trace` for focused tests.
  dev.johnrinehart.external-display.telemetry = {
    enable = true;
    verboseKernelLogging = true;
    persistentJournal = true;
    snapshotAfterResume = true;
  };

  # Retry tunnel discovery after monitor hotplug and system resume. Keep only
  # the laptop's TB root ports, xHCI, and NHI functions out of D3cold/runtime
  # suspend so this test distinguishes host power-state failures from monitor
  # deep-sleep/MST wake failures.
  dev.johnrinehart.external-display.recovery = {
    enable = true;
    attempts = 10;
    delaySeconds = 2;
    minimumExternalConnectors = 2;
    powerManagement = {
      pciDevices = [
        "0000:00:07.0"
        "0000:00:07.1"
        "0000:00:07.2"
        "0000:00:07.3"
        "0000:00:0d.0"
        "0000:00:0d.2"
        "0000:00:0d.3"
      ];
      preventD3Cold = true;
      disableRuntimeSuspend = true;
    };
  };

  # Retain PCI_DEBUG for telemetry, but disable the old broad PCI retry patch:
  # current failures also occur during hotplug and kernel 7.1 no longer exposes
  # the thunderbolt.power_save parameter that the earlier workaround assumed.
  dev.johnrinehart.thunderbolt-debug = {
    enable = true;
    kernelPatches = false;
    bootVerbose = false;
  };

  # Optimize hibernate resume for faster session interactivity
  # Without this, there's a 30-60s delay after resume where display renders
  # but keyboard/mouse input is unresponsive due to resource contention
  dev.johnrinehart.hibernate-resume-optimization = {
    enable = true;

    # HIGH impact (~20-30s): Defer network services to prevent D-Bus flooding
    deferNetworking.enable = true;
    deferNetworking.delaySeconds = 3;

    # MEDIUM impact (~5-10s): Defer bluetooth reconnection attempts
    deferBluetooth.enable = true;
    deferBluetooth.delaySeconds = 5;

    # MEDIUM impact (~10-15s): Prioritize compositor over system services
    prioritizeUserSession.enable = true;
    prioritizeUserSession.userSliceCPUWeight = 200;

    # LOW-MEDIUM impact: Smaller hibernate image = faster write/read
    # Disabled by default - enable if hibernate/resume itself is slow
    reduceHibernateImageSize.enable = false;

    # Diagnostic: Enable to debug slow resume with PM timing
    debugTiming.enable = true;
  };

  environment.etc."modprobe.d/v4l2loopback.conf".text = ''
    options v4l2loopback video_nr=0,1,2 card_label="Virtual Video 0,Virtual Video 1,Virtual Video 2" exclusive_caps=1
  '';

  environment.etc."modules-load.d/v4l2loopback.conf".text = ''
    v4l2loopback
  '';

  # Let Linux own PCIe port services (hotplug, AER, PME) instead of relying on
  # firmware/ACPI handoff. This may avoid resume-time races that leave USB4/TB
  # DisplayPort tunnels disconnected.

  boot.kernelModules = [
    "kvm-intel" # detected automatically
  ];

  services.chrony = {
    enable = true;
    # if we're off by >1s then jump system clock only within the 1st 3 clock
    # updates
    extraConfig = ''
      makestep 1 3
    '';
  };

  services.tailscale = {
    enable = true;
    extraSetFlags = [
      "--accept-dns=true"
      "--accept-routes=true"
    ];
    useRoutingFeatures = "client";
  };

  # WireGuard to neocache k3s server
  networking.wg-quick.interfaces.wg-nc = {
    address = [ "10.100.0.10/24" ];
    privateKeyFile = "/var/lib/wireguard/neocache-private-key";

    peers = [
      {
        publicKey = "Atr/U/uxf3pfLhrIFZz6SD6qxlO4GvT0kZBht+r1oEk="; # k3s server
        endpoint = "k8s.neocache.io:51820";
        allowedIPs = [ "10.100.0.0/24" ];
        persistentKeepalive = 25;
      }
    ];
  };

  # The endpoint is a DNS name, and network-online.target can be reached before
  # nscd/resolvconf finish restarting during nixos-rebuild switch. Order after
  # host name lookup services, but keep the dependency soft so a transient nscd
  # start-limit hit does not also fail the WireGuard unit.
  systemd.services.wg-quick-wg-nc = {
    after = [ "nss-lookup.target" ];
    wants = [ "nss-lookup.target" ];
  };

  # Tailscale/openresolv can update DNS several times during early boot, which
  # repeatedly stops and restarts nscd via nss-lookup.target. nsncd itself exits
  # cleanly, so allow the burst instead of leaving name lookups failed.
  systemd.services.nscd.unitConfig = {
    StartLimitBurst = 20;
    StartLimitIntervalSec = "30s";
  };

  # Personal WireGuard via the OCI hub. This stays on a separate subnet/port
  # from the production neocache k3s overlay.
  #  networking.wg-quick.interfaces.personal = {
  #    address = [ "10.101.0.10/24" ];
  #    privateKeyFile = "/var/lib/wireguard/personal-private-key";
  #
  #    peers = [{
  #      publicKey = "VbR4/DUmH7u6i2fcUFffZyj+pne1HGaLufqWaEA0ano=";  # OCI personal VPN
  #      endpoint = "k8s.neocache.io:51821";
  #      allowedIPs = [ "10.101.0.0/24" ];
  #      persistentKeepalive = 25;
  #    }];
  #  };

  # Fix tailscaled hanging during shutdown when trying to cleanup UPnP port mappings
  # The daemon has an internal 45s watchdog timeout when closing, which blocks shutdown.
  # It tries to delete port mappings from the router, but this hangs if the network
  # is going down or the router is unresponsive.
  systemd.services.tailscaled = {
    # Stop tailscale BEFORE network goes down during shutdown
    # Only use network.target to avoid ordering cycles with NetworkManager
    before = [ "network.target" ];

    serviceConfig = {
      # Gracefully disconnect from tailnet before stopping the daemon
      # This avoids hanging on UPnP port mapping cleanup during shutdown
      ExecStop = "${pkgs.tailscale}/bin/tailscale down --accept-risk=all";

      # Still set a timeout as a safety measure
      # Should complete quickly now that we disconnect first
      TimeoutStopSec = "2s";

      # Send SIGTERM first, then SIGKILL after timeout
      KillMode = "process";
    };
  };

  # Separate service to bring tailscale up after network is online
  # This avoids ExecStartPost timing out when network isn't ready at boot
  systemd.services.tailscale-autoconnect = {
    description = "Automatically connect to Tailscale";
    after = [
      "network-online.target"
      "tailscaled.service"
    ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.tailscale}/bin/tailscale up --accept-routes --accept-dns=true";
      RemainAfterExit = true;

      # Prevent blocking boot if network is slow/unavailable
      TimeoutStartSec = "30s";

      # Retry if it fails (e.g., network not ready yet)
      Restart = "on-failure";
      RestartSec = "10s";
    };
  };

  networking.timeServers = options.networking.timeServers.default ++ [ "time.facebook.com" ];

  services.upower = {
    enable = true;
  };

  swapDevices = [
    {
      device = "/dev/nvme0n1p3";
    }
  ];

  # Decent value for SSD (writes are expensive - chew up lifetime)
  boot.kernel.sysctl."vm.swappiness" = 10;

  systemd.sleep.settings.Sleep = {
    # https://github.com/systemd/systemd/blob/595d88cdc86afdf40127282d711c5985c85fed9b/src/shared/sleep-config.c#L96-L97
    # SuspendState=disk mem freeze
    SuspendState = "mem freeze";
    MemorySleepMode = "deep s2idle";
  };

  boot.kernelParams = [
    "resume=/dev/nvme0n1p3"
    "nocompress"
    "mem_sleep_default=deep"
    "pcie_ports=native"
  ];

  boot.resumeDevice = "/dev/nvme0n1p3";

  services.logind.settings.Login = {
    SleepOperation = "suspend-then-hibernate hibernate hybrid-sleep suspend";
    HandleLidSwitch = "hibernate";
    HandlePowerKey = "hibernate";
    HandleSuspendKey = "hibernate";
  };

  services.getty.loginOptions = "-- \\u TMOUT=10";

  dev.johnrinehart.sound = {
    enable = true;

    # Use PipeWire's software monitor path for mic monitoring so headphones hear
    # the processed Noise Canceled Microphone instead of the Samson Q9U's raw
    # hardware direct-monitor feed.
    micMonitor.enable = true;

    rnnoise = {
      highpass = {
        enable = true;
        frequency = 210.0;
      };
      dualMonoOutput.enable = true;
      deepfilter = {
        enable = true;
        attenuationLimit = 60.0;
        postFilterBeta = 0.02;
      };
      inputRules = [
        {
          matches = [
            {
              "media.class" = "Audio/Source";
              "api.alsa.card.name" = "Samson Q9U";
            }
          ];
          actions.update-props = {
            "priority.session" = 2300;
          };
        }
        {
          matches = [
            {
              "media.class" = "Audio/Source";
              "api.alsa.card.name" = "HDA Intel PCH";
            }
          ];
          actions.update-props = {
            "priority.session" = 2200;
          };
        }
      ];
    };
  };

  virtualisation.vmVariant = _: {
    fileSystems."/" = {
      device = "/dev/sda";
      fsType = "ext4";
    };

    boot.resumeDevice = lib.mkForce "";
    swapDevices = lib.mkForce [ ];

    networking.interfaces = lib.mkForce { };
  };

  hardware.keyboard.zsa.enable = true;

  services.hardware.bolt.enable = true;
}
